module.exports = [
  {
    name: "English",
    url: "https://l.cloudstream.cf/dir_eng",
    raw_url: "https://l.cloudstream.cf/eng",
    emoji: "🇬🇧",
    shortcut: "eng",
  },
  {
    name: "Arabic",
    url: "https://l.cloudstream.cf/dir_arab",
    raw_url: "https://l.cloudstream.cf/arab",
    emoji: "🇯🇴",
    shortcut: "arab",
  },
  {
    name: "Multilingual",
    url: "https://l.cloudstream.cf/dir_multi",
    raw_url: "https://l.cloudstream.cf/multi",
    emoji: "🌏",
    shortcut: "multi",
  },
  {
    name: "Hexated",
    url: "https://l.cloudstream.cf/dir_hexa",
    raw_url: "https://l.cloudstream.cf/hexa",
    emoji: "🌏",
    shortcut: "hexa",
  },
  {
    name: "DarkDemon",
    url: "https://l.cloudstream.cf/dir_drepo",
    raw_url: "https://l.cloudstream.cf/drepo",
    emoji: "🇮🇳",
    shortcut: "drepo",
  },
  {
    name: "LikDev",
    url: "https://l.cloudstream.cf/dir_likrepo",
    raw_url: "https://l.cloudstream.cf/likrepo",
    emoji: "🇮🇳",
    shortcut: "likrepo",
  },
  {
    name: "Stormunblessed",
    url: "https://l.cloudstream.cf/dir_storm",
    raw_url:
      "https://raw.githubusercontent.com/Stormunblessed/stormunblessed-cs3/master/repo.json",
    emoji: "🇪🇸",
    shortcut: "storm",
  },
  {
    name: "Eddy",
    url: "https://l.cloudstream.cf/dir_eddy",
    raw_url: "https://l.cloudstream.cf/eddy",
    emoji: "🇫🇷",
    shortcut: "eddy",
  },
  {
    name: "Horis",
    url: "https://l.cloudstream.cf/dir_horis",
    raw_url: "https://l.cloudstream.cf/horis",
    emoji: "🇨🇳",
    shortcut: "horis",
  },
  {
    name: "Dontseehere",
    url: "https://l.cloudstream.cf/dir_dsh",
    raw_url: "https://l.cloudstream.cf/dsh",
    emoji: "🌏",
    shortcut: "dsh",
  },
  {
    name: "NSFW",
    url: "https://l.cloudstream.cf/dir_nsfw",
    raw_url: "https://l.cloudstream.cf/nsfw",
    emoji: "🔞",
    shortcut: "nsfw",
  },
];
